spring:
  application:
    name: movietracker
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

tmdb:
  access-token: ${TMDB_ACCESS_TOKEN}
  base-url: ${TMDB_BASE_URL:https://api.themoviedb.org/3}

frontend:
  url: ${FRONTEND_URL}